# Generated by Django 4.1.5 on 2023-01-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="none", max_length=255)),
                ("author", models.CharField(default="none", max_length=255)),
                ("publisher", models.CharField(default="none", max_length=255)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                ("right_price", models.BigIntegerField(blank=True, null=True)),
                ("fake_isbn", models.BigIntegerField(blank=True, null=True)),
                ("url", models.CharField(default="none", max_length=1024)),
                ("crawl_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.BigIntegerField(blank=True, null=True)),
                ("sales_point", models.BigIntegerField(blank=True, null=True)),
                ("crawl_date", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
