# Generated by Django 3.2.6 on 2022-02-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_book', '0002_auto_20220221_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edubook',
            old_name='edu_tags',
            new_name='tags',
        ),
    ]
