# Generated by Django 3.1.14 on 2022-02-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_book', '0003_rename_edu_tags_edubook_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='edubook',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='edubook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='edumetadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
